
package com.suai.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransportServiceService", targetNamespace = "http://server.suai.com/", wsdlLocation = "http://localhost:7777/transport?wsdl")
public class TransportServiceService
    extends Service
{

    private final static URL TRANSPORTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSPORTSERVICESERVICE_EXCEPTION;
    private final static QName TRANSPORTSERVICESERVICE_QNAME = new QName("http://server.suai.com/", "TransportServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/transport?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSPORTSERVICESERVICE_WSDL_LOCATION = url;
        TRANSPORTSERVICESERVICE_EXCEPTION = e;
    }

    public TransportServiceService() {
        super(__getWsdlLocation(), TRANSPORTSERVICESERVICE_QNAME);
    }

    public TransportServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSPORTSERVICESERVICE_QNAME, features);
    }

    public TransportServiceService(URL wsdlLocation) {
        super(wsdlLocation, TRANSPORTSERVICESERVICE_QNAME);
    }

    public TransportServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSPORTSERVICESERVICE_QNAME, features);
    }

    public TransportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransportServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransportService
     */
    @WebEndpoint(name = "TransportServicePort")
    public TransportService getTransportServicePort() {
        return super.getPort(new QName("http://server.suai.com/", "TransportServicePort"), TransportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransportService
     */
    @WebEndpoint(name = "TransportServicePort")
    public TransportService getTransportServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.suai.com/", "TransportServicePort"), TransportService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSPORTSERVICESERVICE_EXCEPTION!= null) {
            throw TRANSPORTSERVICESERVICE_EXCEPTION;
        }
        return TRANSPORTSERVICESERVICE_WSDL_LOCATION;
    }

}
